timeout: 5

/ytkernel
    protocol: multiboot
    path: boot():/boot/kernel.elf
    module_path: boot():/user.elf
    module_string: user.elf
    module_path: boot():/kshell.lua
    module_string: kshell.lua
    module_path: boot():/lat9-16.psf
    module_string: font
