#pragma once

typedef enum {
    FILE_ERR_NONE,
    FILE_ERR_CANNOT_OPEN,
    FILE_ERR_BAD_FLAGS,
    FILE_ERR_BAD_ARGS,
    FILE_ERR_NOT_FOUND,
    FILE_ERR_NOT_OPENED,
    FILE_ERR_NOT_SUPP,
    FILE_ERR_NEG_OFFSET,
    FILE_ERR_IO,
} file_err_t;
