#pragma once

typedef enum {
    VFS_ERR_NONE,

    VFS_ERR_NODE_BAD_OP,
    VFS_ERR_NODE_BAD_ARGS,
    VFS_ERR_NODE_NOT_DIR,
    VFS_ERR_NODE_ALREADY_MOUNTED,
    VFS_ERR_NODE_NOT_MOUNTED,
    VFS_ERR_NODE_NO_FS,
    VFS_ERR_NODE_NO_DATA,

    VFS_ERR_PATH_EMPTY,
    VFS_ERR_PATH_TOO_MANY_PARTS,
    VFS_ERR_PATH_PART_TOO_LONG,
} vfs_err_t;
